const seed=[{id:'RX-1001',customer:'Amina Wanjiku',phone:'0712 345 678',address:'Westlands, Nairobi',item:'Samsung A15',status:'Open',rider:''},{id:'RX-1002',customer:'Brian Otieno',phone:'0722 111 444',address:'Kilimani, Nairobi',item:'Pharmacy order',status:'Assigned',rider:'Kamau'},{id:'RX-1003',customer:'Mercy Njeri',phone:'0700 222 333',address:'South B, Nairobi',item:'Power drill',status:'Picked Up',rider:'Otieno'}];
const riders=['Kamau','Otieno','Asha']; let deliveries=JSON.parse(localStorage.getItem('reflex-deliveries')||'null')||seed; let filter='All';
const $=id=>document.getElementById(id); const filters=['All','Open','Assigned','Picked Up','Delivered'];
function save(){localStorage.setItem('reflex-deliveries',JSON.stringify(deliveries));$('syncText').textContent='Saved locally'}
function render(){const counts={Open:0,Assigned:0,'Picked Up':0,Delivered:0};deliveries.forEach(d=>{if(counts[d.status]!=null)counts[d.status]++});$('openCount').textContent=counts.Open;$('assignedCount').textContent=counts.Assigned;$('pickedCount').textContent=counts['Picked Up'];$('deliveredCount').textContent=counts.Delivered;
$('filters').innerHTML=filters.map(f=>`<button class="filter ${f===filter?'active':''}" data-filter="${f}">${f}</button>`).join('');
const query=$('search').value.toLowerCase();const visible=deliveries.filter(d=>(filter==='All'||d.status===filter)&&`${d.id} ${d.customer} ${d.address} ${d.item} ${d.rider}`.toLowerCase().includes(query));
$('cards').innerHTML=visible.length?visible.map(cardTemplate).join(''):'<div class="empty">No deliveries match this view.</div>';document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset.id));}
function cardTemplate(d){let actionText='';if(d.status==='Open')actionText='Assign rider';if(d.status==='Assigned')actionText='Mark picked up';if(d.status==='Picked Up')actionText='Mark delivered';return `<article class="card"><span class="badge">${d.status}</span><h3>${d.customer}</h3><p class="meta">${d.id} · ${d.phone}</p><p>${d.item}</p><p class="meta">${d.address}</p>${d.rider?`<p class="meta">Rider: ${d.rider}</p>`:''}<div class="actions">${actionText?`<button data-action="advance" data-id="${d.id}">${actionText}</button>`:''}</div></article>`}
function action(type,id){const d=deliveries.find(x=>x.id===id);if(!d)return;if(d.status==='Open'){const rider=prompt(`Choose rider: ${riders.join(', ')}`);if(!rider||!riders.includes(rider))return alert(`Use one of: ${riders.join(', ')}`);d.rider=rider;d.status='Assigned'}else if(d.status==='Assigned')d.status='Picked Up';else if(d.status==='Picked Up')d.status='Delivered';save();render()}
$('requestForm').addEventListener('submit',e=>{e.preventDefault();deliveries.unshift({id:'RX-'+String(Date.now()).slice(-4),customer:$('customer').value.trim(),phone:$('phone').value.trim(),address:$('address').value.trim(),item:$('item').value.trim(),status:'Open',rider:''});e.target.reset();save();render()});
$('search').addEventListener('input',render);$('confirmScan').onclick=()=>{const code=$('scanCode').value.trim();const d=deliveries.find(x=>x.id===code);if(!d){$('scanMessage').textContent='No delivery matched that code. Check the code and try again.';return}d.status='Delivered';$('scanMessage').textContent=`${d.id} confirmed and marked Delivered.`;save();render()};
$('role').onchange=()=>{const r=$('role').value;$('retailerPanel').hidden=r!=='Retailer';$('dashboard').hidden=r==='Retailer';$('riderPanel').hidden=r!=='Rider';if(r==='Dispatcher'){$('dashboard').hidden=false;$('retailerPanel').hidden=true;$('riderPanel').hidden=true}};
render();