const seed=[{id:'RX-1001',customer:'Amina Wanjiku',phone:'0712 345 678',address:'Westlands, Nairobi',item:'Samsung A15',status:'Open',rider:''},{id:'RX-1002',customer:'Brian Otieno',phone:'0722 111 444',address:'Kilimani, Nairobi',item:'Pharmacy order',status:'Assigned',rider:'Kamau'},{id:'RX-1003',customer:'Mercy Njeri',phone:'0700 222 333',address:'South B, Nairobi',item:'Power drill',status:'Picked Up',rider:'Otieno'}];
let deliveries=JSON.parse(localStorage.getItem('reflex-deliveries')||'null')||seed;let filter='all';
const riders=['Kamau','Otieno','Asha'];
function save(){localStorage.setItem('reflex-deliveries',JSON.stringify(deliveries));document.getElementById('syncText').textContent='Synced locally';}
function render(){const counts={Open:0,Assigned:0,Delivered:0};deliveries.forEach(d=>{if(counts[d.status]!==undefined)counts[d.status]++});openCount.textContent=counts.Open;assignedCount.textContent=counts.Assigned;deliveredCount.textContent=counts.Delivered;cards.innerHTML='';deliveries.filter(d=>filter==='all'||d.status===filter).forEach(d=>{const card=document.createElement('article');card.className='card';card.innerHTML=`<span class="badge">${d.status}</span><h4>${d.customer}</h4><p class="meta">${d.id} · ${d.phone}</p><p>${d.item}</p><p class="meta">${d.address}</p>${d.rider?`<p class="meta">Rider: ${d.rider}</p>`:''}<div class="actions"></div>`;const actions=card.querySelector('.actions');if(d.status==='Open'){const b=document.createElement('button');b.textContent='Assign rider';b.onclick=()=>assign(d.id);actions.appendChild(b)}if(d.status==='Assigned'){const b=document.createElement('button');b.textContent='Mark picked up';b.onclick=()=>advance(d.id,'Picked Up');actions.appendChild(b)}if(d.status==='Picked Up'){const b=document.createElement('button');b.textContent='Mark delivered';b.onclick=()=>advance(d.id,'Delivered');actions.appendChild(b)}cards.appendChild(card)});}
function assign(id){const rider=prompt(`Assign ${riders.join(', ')}\nEnter rider name:`);if(rider&&riders.includes(rider)){const d=deliveries.find(x=>x.id===id);d.rider=rider;d.status='Assigned';save();render()}else if(rider){alert('Use one of the demo riders: '+riders.join(', '))}}
function advance(id,status){const d=deliveries.find(x=>x.id===id);d.status=status;save();render()}
requestForm.addEventListener('submit',e=>{e.preventDefault();deliveries.unshift({id:'RX-'+String(Date.now()).slice(-4),customer:customer.value,phone:phone.value,address:address.value,item:item.value,status:'Open',rider:''});e.target.reset();save();render()});document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});
confirmScan.onclick=()=>{const code=scanCode.value.trim();const d=deliveries.find(x=>x.id===code);if(!d){scanMessage.textContent='No delivery matched that code. Check the code and try again.';return}d.status='Delivered';scanMessage.textContent=`${d.id} confirmed and marked Delivered.`;save();render()};
role.onchange=()=>{const r=role.value;retailerPanel.hidden=r!=='Retailer';scanPanel.hidden=r!=='Rider';document.querySelector('.dashboard').style.display=r==='Retailer'?'none':'block'};
if(location.protocol!=='file:'){navigator.mediaDevices?.getUserMedia?.({video:true}).catch(()=>{});}render();